### ISSUE TITLE
Hi, sorry I didn't know how to contact you so I made an issue instead 

### ISSUE THREAD

**Issue by einleft** [seezaara/js2ray#1]
closed

**Comment by Morrigan-Ship** [comment]
Hi glad to see you.
whats your Idea for new project?

**Comment by einleft** [comment]
I'm currently working on a unique VPN project that I believe has the potential to revolutionize the industry and tap into an underserved market.

The VPN I'm building leverages WireGuard for encryption and Xray-Core for obfuscation—technologies, most VPNs focus only on the encryption and not so much on topics that are on a network layer 7 level such as metadata or correlation attacks. The goal is to create a solution focused on privacy, security, performance, and uncensorship, addressing an untapped need in the market.

While I'm focused on the frontend for the softwares and websites, I’m looking for a skilled developer to join me in building the backend with Node.js and SQLite, and experience in Xray-Core, VLESS (proxy), XTLS (transport layer) and possibly wireguard (not required).

Rather than just hiring someone, I’m looking for a partner who can help shape the project’s development and success. I’m offering a cut of the project’s revenue as a share in the business, so we both benefit as it grows.

If this sounds like a fit for you and you'd be interested in collaborating, I’d love to connect and discuss further. 

if you are interested email me or just send me your email.

**Comment by seezaara** [comment]
> Hi glad to see you. whats your Idea for new project?

it can run on cpanel host for low cost (if support nodejs) .
you can contact me in telegram: https://t.me/seezaara
